<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Need a user name and password_stripes_c24f9c</name>
   <tag></tag>
   <elementGuidId>b9eacd82-8be7-4b1e-a83e-7636440ed801</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#stripes--1253602232</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = 'username' and @type = 'text']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='stripes--1253602232']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#stripes--1253602232</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b700ff78-51f2-4d5d-b0d9-fd17939c97c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>username</value>
      <webElementGuid>169987a1-876a-4646-b898-c66ad3788f5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8f8ef607-ddad-4ffd-a8ff-1426550cd4da</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>166b2b7f-2405-4eee-8ae0-4858ba9aca7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Catalog']/form/p[2]/input</value>
      <webElementGuid>f80b9e2f-cb63-4bf8-89b3-25e9fd967bb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[2]/input</value>
      <webElementGuid>b1740bca-1c59-4dc2-9782-a1d5cb34e983</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'username' and @type = 'text']</value>
      <webElementGuid>42e27768-41ae-4b7e-bc60-91ca4f4c337c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
